// <auto-generated />
namespace ThucPham.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changeName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeName));
        
        string IMigrationMetadata.Id
        {
            get { return "202006241741205_changeName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
